# Site
title: #LulaLivre

# URL
url: http://www.lulalivre.github.io/
baseurl: 
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4567

# Data
social:
  facebook_url: "https://www.facebook.com/Lula/"
  twitter_url: "https://twitter.com/LulaOficial"
  twitter_user: "@LulaOficial"
