# Site
title: #LulaLivre

# URL
url: http://grevegeral.org
baseurl: 
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4567

# Data
social:
  facebook_url: "https://www.facebook.com/GreveGeral-758484700985102/"
  twitter_url: "https://twitter.com/28temGreveGeral"
  twitter_user: "@28temGreveGeral"
